### ISSUE TITLE
Perplexed Normal is kursiv like the italic version

### ISSUE THREAD

**Issue by borisz** [phoikoi/perplexed#1]
Perplexed-Normal.otf is kursiv
Perplexed-Italic.otf is kursiv as well
Perplexed-Bold.otf is normal-bold like it should

Thank you very much for doing this! I use a mac and fontlint shows this warning:

CHECKING     Perplexed-Normal.otf
Warning: Mac string is a subset of the Windows string in the 'name' table
 for the Family string in the English (US) language.
Warning: Mac and Windows entries in the 'name' table differ for the
 SubFamily string in the language English (US)
 Mac String: Normal
Windows String: Italic

I have no idea if this is related, but it looks so.

**Comment by phoikoi** [comment]
Hmm, for some reason the italic face got uploaded as normal.  Thanks for letting me know.  I've regenerated the normal face from the glyphs file and uploaded it.
